name: Foo-Bar Action Responder

on: [repository_dispatch]

jobs:
  foo-bar:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}'"
          echo "Repository '${{ github.event.client_payload.GITHUB_REPOSITORY }}'"
          echo "Commit '${{ github.event.client_payload.GITHUB_SHA }}'"
      - name: Clone Repo
        run: |
          git clone https://github.com/${{ github.event.client_payload.GITHUB_REPOSITORY }}.git
          cd GITHUB_REPOSITORY_NAME
          git checkout ${{ github.event.client_payload.GITHUB_SHA }}
